### PR TITLE
New perls

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Comment by karenetheridge** [comment]
Would it be useful to add tests for the various error messages, so it is more obvious when they change?

**Comment by karenetheridge** [comment]
Please could this fix be released, so that it can be included with perl 5.27.9 (about to be released in the next day)?  I also need to do a release of YAML-Tiny, but if I do it now, installations into new systems will break (latest Encode is 2.96 which leads to https://github.com/dankogai/p5-encode/pull/130/commits/cfaedb2beda37cbc3575ee818c3c83ea87673c32).

**Comment by dankogai** [comment]
tagged and pushed.  PAUSE as soon as travised.

**Comment by karenetheridge** [comment]
thank you very much!

**Pull request merged**
