### PR TITLE
Ensure that UTF-16 decode always includes a trailing NUL.

### PR DESCRIPTION
**Pull request by FGasper**
Issue #159

### CODE REVIEW

**Review by pali — APPROVED** [review]

**Comment by dankogai** [comment]
Thank you.

**Comment by dankogai** [comment]
This is big enough to $VERSION++ but I am on my way to the 2nd COVID 💉 today.  Please wait till I'm done w/ the shot (and possible side effects).

**Comment by FGasper** [comment]
> This is big enough to $VERSION++ but I am on my way to the 2nd COVID 💉 today. Please wait till I'm done w/ the shot (and possible side effects).

@dankogai You ok?

**Comment by dankogai** [comment]
I am OK now but I only have an iPad and iPhone this weekend so please wait a few more days...

**Comment by FGasper** [comment]
No worries; for now just concat’ing the string to empty works around it.

-F

**Pull request merged**
