### PR TITLE
New perls

### PR DESCRIPTION
**Pull request by khwilliamson**

### CODE REVIEW

**Comment by dankogai** [comment]
Thank you.  VERSION++ follows immediately.

**Comment by karenetheridge** [comment]
These changes cause breakages in YAML::Tiny (and CPAN::Meta::YAML, a dual-life module) on perl 5.26.1 and earlier:  https://rt.cpan.org/Ticket/Display.html?id=124399

Is it using a feature that is only available in blead? Should ppport.h be used to provide equivalent functionality in earlier perls?

**Comment by dankogai** [comment]
I doubt it.  travis  w/ following config is happy.

```
language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
```

https://travis-ci.org/dankogai/p5-encode

Also I could not reproduce it on any of my environments.

**Comment by karenetheridge** [comment]
Encode's tests work fine for me too -- apparently they are not testing the change that is tickling YAML::Tiny's tests.

**Comment by karenetheridge** [comment]
PR #130 fixes this (not yet released).

**Pull request merged**
