### PR TITLE
Remove old disabled tests from t/gsm0338.t

### PR DESCRIPTION
**Pull request by pali**
This is dead code as it is after __END__ block.
Moreover these tests are covered by other tests.

### CODE REVIEW

**Comment by pali** [comment]
Travis is somehow is not running... @dankogai can you disabled and enable it? In most cases this helps.

**Comment by dankogai** [comment]
Thank you!  Travis looks fine now.

https://travis-ci.org/github/dankogai/p5-encode

**Comment by pali** [comment]
But results are not available on github: https://github.com/dankogai/p5-encode/commits/master

I had same issue. I removed travis from gtihub https://github.com/settings/applications (revoke) and enabled it again via travis web. That helped.

**Comment by dankogai** [comment]
I did not have your problem  travis just ran as expected.

https://travis-ci.org/github/dankogai/p5-encode/builds/732231466

the following commit just added perl 5.32 to `.travis.yml` and update to `Changes`, which also ran okay.

https://travis-ci.org/github/dankogai/p5-encode/builds/732232462

**Comment by pali** [comment]
> I did not have your problem travis just ran as expected.

Really? I still do not see green marks on github page https://github.com/dankogai/p5-encode/commits/master for new commits that Travis finished. It means that Travis would not work also for pull requests.

**Pull request merged**
